export const REQUEST_NEWS = 'REQUEST_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';

export const RECEIVE_NEWS_DETAILS = 'RECEIVE_NEWS_DETAILS';
export const REQUEST_NEWS_DETAILS = 'REQUEST_NEWS_DETAILS';