export const ROOT = 'https://restcountries.eu/rest/v2';

export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';

export const REQUEST_EU_COUNTRIES = 'REQUEST_EU_COUNTRIES';
export const RECEIVE_EU_COUNTRIES = 'RECEIVE_EU_COUNTRIES';


export const REQUEST_COUNTRY = 'REQUEST_COUNTRY';
export const RECEIVE_COUNTRY = 'RECEIVE_COUNTRY';


export const REQUEST_NEWS = 'REQUEST_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';